### ISSUE TITLE
cannot run app

### ISSUE THREAD

**Issue by knot22** [GeekyAnts/KitchenSink-Vue-Native#22]
I was able to successfully clone your code to a Windows 10 machine which has Expo CLI and Vue Native CLI installed.  Using Git Bash, and being in the correct directory where the project files have been cloned, running `npm start` results in errors and the app does not start.  Below is the log file output.  What needs to be changed to get it to work?
````
0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'start'
1 verbose cli ]
2 info using npm@6.12.0
3 info using node@v12.13.0
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle kitchenSink-vue-native@0.2.0~prestart: kitchenSink-vue-native@0.2.0
6 info lifecycle kitchenSink-vue-native@0.2.0~start: kitchenSink-vue-native@0.2.0
7 verbose lifecycle kitchenSink-vue-native@0.2.0~start: unsafe-perm in lifecycle true
8 verbose lifecycle kitchenSink-vue-native@0.2.0~start: PATH: C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;Z:\files\development\vue_native\code\git\KitchenSink-Vue-Native\node_modules\.bin;C:\Users\jason.black\bin;C:\Program Files\Git\mingw64\bin;C:\Program Files\Git\usr\local\bin;C:\Program Files\Git\usr\bin;C:\Program Files\Git\usr\bin;C:\Program Files\Git\mingw64\bin;C:\Program Files\Git\usr\bin;C:\Users\jason.black\bin;C:\Python27;C:\Python27\Scripts;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0;C:\Windows\System32\OpenSSH;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files (x86)\Microsoft SQL Server\150\DTS\Binn;C:\Program Files\Microsoft SQL Server\Client SDK\ODBC\130\Tools\Binn;C:\Program Files (x86)\Microsoft SQL Server\140\Tools\Binn;C:\Program Files\Microsoft SQL Server\140\Tools\Binn;C:\Program Files\Microsoft SQL Server\140\DTS\Binn;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\HashiCorp\Vagrant\bin;C:\Program Files\Git\cmd;C:\xampp\php;C:\ProgramData\ComposerSetup\bin;C:\Program Files\nodejs;C:\ProgramData\chocolatey\bin;C:\Users\jason.black\AppData\Local\Microsoft\WindowsApps;C:\Users\jason.black\AppData\Local\atom\bin;C:\Users\jason.black\AppData\Roaming\Composer\vendor\bin;C:\Users\jason.black\AppData\Roaming\npm;C:\Program Files\Git\usr\bin\vendor_perl;C:\Program Files\Git\usr\bin\core_perl
9 verbose lifecycle kitchenSink-vue-native@0.2.0~start: CWD: Z:\files\development\vue_native\code\git\KitchenSink-Vue-Native
10 silly lifecycle kitchenSink-vue-native@0.2.0~start: Args: [ '/d /s /c', 'expo start' ]
11 silly lifecycle kitchenSink-vue-native@0.2.0~start: Returned: code: 1  signal: null
12 info lifecycle kitchenSink-vue-native@0.2.0~start: Failed to exec start script
13 verbose stack Error: kitchenSink-vue-native@0.2.0 start: `expo start`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:210:5)
13 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:210:5)
13 verbose stack     at maybeClose (internal/child_process.js:1021:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
14 verbose pkgid kitchenSink-vue-native@0.2.0
15 verbose cwd Z:\files\development\vue_native\code\git\KitchenSink-Vue-Native
16 verbose Windows_NT 10.0.17763
17 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
18 verbose node v12.13.0
19 verbose npm  v6.12.0
20 error code ELIFECYCLE
21 error errno 1
22 error kitchenSink-vue-native@0.2.0 start: `expo start`
22 error Exit status 1
23 error Failed at the kitchenSink-vue-native@0.2.0 start script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
````

**Comment by knot22** [comment]
I have switched to using Ubuntu 18.04 on a VM so this issue is no longer a concern.
