### ISSUE TITLE
newbie question: cannot install

### ISSUE THREAD

**Issue by BobWalsh** [GeekyAnts/KitchenSink-Vue-Native#4]
here's what I got after I cloned your repo, when I ran yarn...

```
yarn
yarn install v1.7.0
(node:45495) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
info @expo/ngrok-bin-darwin-ia32@2.2.8: The CPU architecture "x64" is incompatible with this module.
info "@expo/ngrok-bin-darwin-ia32@2.2.8" is an optional dependency and failed compatibility check. Excluding it from installation.
info @expo/ngrok-bin-freebsd-ia32@2.2.8: The platform "darwin" is incompatible with this module.
info "@expo/ngrok-bin-freebsd-ia32@2.2.8" is an optional dependency and failed compatibility check. Excluding it from installation.
info @expo/ngrok-bin-freebsd-ia32@2.2.8: The CPU architecture "x64" is incompatible with this module.
info @expo/ngrok-bin-freebsd-x64@2.2.8: The platform "darwin" is incompatible with this module.
info "@expo/ngrok-bin-freebsd-x64@2.2.8" is an optional dependency and failed compatibility check. Excluding it from installation.
info @expo/ngrok-bin-linux-arm@2.2.8: The platform "darwin" is incompatible with this module.
info "@expo/ngrok-bin-linux-arm@2.2.8" is an optional dependency and failed compatibility check. Excluding it from installation.
info @expo/ngrok-bin-linux-arm@2.2.8: The CPU architecture "x64" is incompatible with this module.
info @expo/ngrok-bin-linux-arm64@2.2.8: The platform "darwin" is incompatible with this module.
info "@expo/ngrok-bin-linux-arm64@2.2.8" is an optional dependency and failed compatibility check. Excluding it from installation.
info @expo/ngrok-bin-linux-arm64@2.2.8: The CPU architecture "x64" is incompatible with this module.
info @expo/ngrok-bin-linux-ia32@2.2.8: The platform "darwin" is incompatible with this module.
info "@expo/ngrok-bin-linux-ia32@2.2.8" is an optional dependency and failed compatibility check. Excluding it from installation.
info @expo/ngrok-bin-linux-ia32@2.2.8: The CPU architecture "x64" is incompatible with this module.
info @expo/ngrok-bin-linux-x64@2.2.8: The platform "darwin" is incompatible with this module.
info "@expo/ngrok-bin-linux-x64@2.2.8" is an optional dependency and failed compatibility check. Excluding it from installation.
info @expo/ngrok-bin-sunos-x64@2.2.8: The platform "darwin" is incompatible with this module.
info "@expo/ngrok-bin-sunos-x64@2.2.8" is an optional dependency and failed compatibility check. Excluding it from installation.
info @expo/ngrok-bin-win32-ia32@2.2.8-beta.1: The platform "darwin" is incompatible with this module.
info "@expo/ngrok-bin-win32-ia32@2.2.8-beta.1" is an optional dependency and failed compatibility check. Excluding it from installation.
info @expo/ngrok-bin-win32-ia32@2.2.8-beta.1: The CPU architecture "x64" is incompatible with this module.
info @expo/ngrok-bin-win32-x64@2.2.8-beta.1: The platform "darwin" is incompatible with this module.
info "@expo/ngrok-bin-win32-x64@2.2.8-beta.1" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] 🔗  Linking dependencies...
warning "react-native > metro > @babel/plugin-check-constants@7.0.0-beta.38" has incorrect peer dependency "@babel/core@7.0.0-beta.38".
warning " > vue-native-router@0.0.1-alpha.3" has incorrect peer dependency "vue-native-helper@0.0.6".
warning " > vue-native-router@0.0.1-alpha.3" has incorrect peer dependency "vue-native-scripts@0.0.7".
warning "jest-expo > babel-jest@22.4.3" has unmet peer dependency "babel-core@^6.0.0 || ^7.0.0-0".
[4/4] 📃  Building fresh packages...
[1/2] ⠄ fsevents
warning Error running install script for optional dependency: "/Users/bobwalsh/KitchenSink-Vue-Native/node_modules/fsevents: Command failed.
Exit code: 1
Command: node install
Arguments:
Directory: /Users/bobwalsh/KitchenSink-Vue-Native/node_modules/fsevents
Output:
node-pre-gyp info it worked if it ends with ok
node-pre-gyp info using node-pre-gyp@0.6.39
node-pre-gyp info using node@10.2.1 | darwin | x64
node-pre-gyp info check checked for \"/Users/bobwalsh/KitchenSink-Vue-Native/node_modules/fsevents/lib/binding/Release/node-v64-darwin-x64/fse.node\" (not found)
node-pre-gyp http GET https://fsevents-binaries.s3-us-west-2.amazonaws.com/v1.1.3/fse-v1.1.3-node-v64-darwin-x64.tar.gz
node-pre-gyp http 404 https://fsevents-binaries.s3-us-west-2.amazonaws.com/v1.1.3/fse-v1.1.3-node-v64-darwin-x64.tar.gz
node-pre-gyp ERR! Tried to download(404): https://fsevents-binaries.s3-us-west-2.amazonaws.com/v1.1.3/fse-v1.1.3-node-v64-darwin-x64.tar.gz
node-pre-gyp ERR! Pre-built binaries not found for fsevents@1.1.3 and node@10.2.1 (node-v64 ABI, unknown) (falling back to source compile with node-gyp)
node-pre-gyp http 404 status code downloading tarball https://fsevents-binaries.s3-us-west-2.amazonaws.com/v1.1.3/fse-v1.1.3-node-v64-darwin-x64.tar.gz
node-pre-gyp ERR! Tried to download(undefined): https://fsevents-binaries.s3-us-west-2.amazonaws.com/v1.1.3/fse-v1.1.3-node-v64-darwin-x64.tar.gz
node-pre-gyp ERR! Pre-built binaries not found for fsevents@1.1.3 and node@10.2.1 (node-v64 ABI, unknown) (falling back to source compile with node-gyp)
node-pre-gyp http Connection closed while downloading tarball file
gypgyp  info infoit worked if it ends with it worked if it ends with ok
 ok
gypgyp  infoinfo  usingusing node-gyp@3.6.2
 node-gyp@3.6.2
gypgyp  infoinfo  usingusing node@10.2.1 | darwin | x64
 node@10.2.1 | darwin | x64
gypgyp info  okinfo
 ok
gyp info it worked if it ends with ok
gypgyp info  using node-gyp@3.6.2
infogyp  info it worked if it ends withusing node@10.2.1 | darwin | x64
 ok
gyp info using node-gyp@3.6.2
gyp info using node@10.2.1 | darwin | x64
gypgyp  infoinfo  spawnspawn /usr/bin/python
 /usr/bin/python
gyp gypinfo  infospawn args  [ '/usr/local/Cellar/node/10.2.1/libexec/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
spawn argsgyp [ '/usr/local/Cellar/node/10.2.1/libexec/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
 gypinfo  spawn argsinfo   'binding.gyp',
 spawn argsgyp   'binding.gyp',
 gypinfo  infospawn args   '-f',
 gypspawn args    '-f',
info spawn args   'make',
gyp info spawn args   '-I',
gypgyp info  infospawn args    '/Users/bobwalsh/KitchenSink-Vue-Native/node_modules/fsevents/build/config.gypi',
spawn argsgyp   'make',
 gypinfo  infospawn args    '-I',
spawn argsgyp   '-I',
 gypinfo  infospawn args    '/usr/local/Cellar/node/10.2.1/libexec/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
spawn argsgyp   '/Users/bobwalsh/KitchenSink-Vue-Native/node_modules/fsevents/build/config.gypi',
 gypinfo  infospawn args    '-I',
spawn argsgyp   '-I',
 gypinfo  infospawn args    '/Users/bobwalsh/.node-gyp/10.2.1/include/node/common.gypi',
spawn argsgyp   '/usr/local/Cellar/node/10.2.1/libexec/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
 gyp info spawn args   '-I',
gyp info spawn args   '/Users/bobwalsh/.node-gyp/10.2.1/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/Users/bobwalsh/.node-gyp/10.2.1',
gyp info spawn args   '-Dnode_gyp_dir=/usr/local/Cellar/node/10.2.1/libexec/lib/node_modules/npm/node_modules/node-gyp',
gyp info spawn argsinfo   '-Dnode_lib_file=/Users/bobwalsh/.node-gyp/10.2.1/<(target_arch)/node.lib',
gyp info  spawn args   '-Dmodule_root_dir=/Users/bobwalsh/KitchenSink-Vue-Native/node_modules/fsevents',
spawn argsgyp   '-Dlibrary=shared_library',
gyp  infoinfo  spawn argsspawn args   '-Dnode_engine=v8',
   '-Dvisibility=default',
gypgyp  infoinfo  spawn argsspawn args   '--depth=.',
   '-Dnode_root_dir=/Users/bobwalsh/.node-gyp/10.2.1',
gypgyp  infoinfo  spawn argsspawn args   '--no-parallel',
   '-Dnode_gyp_dir=/usr/local/Cellar/node/10.2.1/libexec/lib/node_modules/npm/node_modules/node-gyp',
gypgyp  infoinfo  spawn argsspawn args   '--generator-output',
   '-Dnode_lib_file=/Users/bobwalsh/.node-gyp/10.2.1/<(target_arch)/node.lib',
gypgyp  infoinfo  spawn argsspawn args   '-Dmodule_root_dir=/Users/bobwalsh/KitchenSink-Vue-Native/node_modules/fsevents',
gyp   'build',
 gypinfo  spawn argsinfo   '-Dnode_engine=v8',
 gypspawn args    '-Goutput_dir=.' ]
info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.' ]
gypgyp  infoinfo  okok

gypgyp info it worked if it ends with ok
 info it worked if it ends with ok
gyp info using node-gyp@3.6.2
gyp info using node@10.2.1 | darwin | x64
gyp info using node-gyp@3.6.2
gyp info using node@10.2.1 | darwin | x64
gypgyp info  spawn make
info spawn make
gyp infogyp  spawn argsinfo [ 'BUILDTYPE=Release', '-C', 'build' ]
 spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
  SOLINK_MODULE(target) Release/.node
  SOLINK_MODULE(target) Release/.node
  CXX(target) Release/obj.target/fse/fsevents.o
  CXX(target) Release/obj.target/fse/fsevents.o
In file included from ../fsevents.cc:85:
In file included from ../fsevents.cc:../src/methods.cc:8514:
:12: warning: 'Call' is deprecated [-Wdeprecated-declarations]
../src/methods.cc:14:12: warning: 'Call' is deprecated [-Wdeprecated-declarations]
  handler->Call(3, argv);  handler->Call(3, argv);
           ^

           ^
../../nan/nan.h:1617:3: note: 'Call' has been explicitly marked deprecated here../../nan/nan.h:
1617:3: note: 'Call' has been explicitly marked deprecated here
  NAN_DEPRECATED inline v8::Local<v8::Value>
  ^
  NAN_DEPRECATED inline v8::Local<v8::Value>
  ^
../../nan/nan.h:../../nan/nan.h98::9840::40 :note : noteexpanded from macro 'NAN_DEPRECATED':
expanded from macro 'NAN_DEPRECATED'
# define NAN_DEPRECATED __attribute__((deprecated))
                                       ^
# define NAN_DEPRECATED __attribute__((deprecated))
                                       ^
1 warning generated.
1 warning generated.
rm: ./Release/.deps/Release/obj.target/fse/fsevents.o.d.raw: No such file or directory
make: *** [Release/obj.target/fse/fsevents.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/Cellar/node/10.2.1/libexec/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:258:23)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:237:12)
gyp ERR! System Darwin 17.6.0
gyp ERR! command \"/usr/local/Cellar/node/10.2.1/bin/node\" \"/usr/local/Cellar/node/10.2.1/libexec/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js\" \"build\" \"--fallback-to-build\" \"--module=/Users/bobwalsh/KitchenSink-Vue-Native/node_modules/fsevents/lib/binding/Release/node-v64-darwin-x64/fse.node\" \"--module_name=fse\" \"--module_path=/Users/bobwalsh/KitchenSink-Vue-Native/node_modules/fsevents/lib/binding/Release/node-v64-darwin-x64\"
gyp ERR! cwd /Users/bobwalsh/KitchenSink-Vue-Native/node_modules/fsevents
gyp ERR! node -v v10.2.1
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
  SOLINK_MODULE(target) Release/fse.node
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute 'node-gyp build --fallback-to-build --module=/Users/bobwalsh/KitchenSink-Vue-Native/node_modules/fsevents/lib/binding/Release/node-v64-darwin-x64/fse.node --module_name=fse --module_path=/Users/bobwalsh/KitchenSink-Vue-Native/node_modules/fsevents/lib/binding/Release/node-v64-darwin-x64' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/Users/bobwalsh/KitchenSink-Vue-Native/node_modules/fsevents/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:961:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:5)
node-pre-gyp ERR! System Darwin 17.6.0
node-pre-gyp ERR! command \"/usr/local/Cellar/node/10.2.1/bin/node\" \"/Users/bobwalsh/KitchenSink-Vue-Native/node_modules/fsevents/node_modules/node-pre-gyp/bin/node-pre-gyp\" \"install\" \"--fallback-to-build\"
node-pre-gyp ERR! cwd /Users/bobwalsh/KitchenSink-Vue-Native/node_modules/fsevents
node-pre-gyp ERR! node -v v10.2.1
node-pre-gyp ERR! node-pre-gyp -v v0.6.39
node-pre-gyp ERR! not ok
Failed to execute 'node-gyp build --fallback-to-build --module=/Users/bobwalsh/KitchenSink-Vue-Native/node_modules/fsevents/lib/binding/Release/node-v64-darwin-x64/fse.node --module_name=fse --module_path=/Users/bobwalsh/KitchenSink-Vue-Native/node_modules/fsevents/lib/binding/Release/node-v64-darwin-x64' (1)
  COPY /Users/bobwalsh/KitchenSink-Vue-Native/node_modules/fsevents/lib/binding/Release/node-v64-darwin-x64/fse.node
  TOUCH Release/obj.target/action_after_build.stamp
gyp info ok"
✨  Done in 69.61s.
```
and when I started it:
```
Bobs-iMac-3:KitchenSink-Vue-Native bobwalsh$ npm start

> kitchenSink-vue-native@0.1.0 start /Users/bobwalsh/KitchenSink-Vue-Native
> react-native-scripts start

11:37:59 AM: Unable to start server
See https://git.io/v5vcn for more information, either install watchman or run the following snippet:
  sudo sysctl -w kern.maxfiles=5242880
  sudo sysctl -w kern.maxfilesperproc=524288

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! kitchenSink-vue-native@0.1.0 start: `react-native-scripts start`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the kitchenSink-vue-native@0.1.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/bobwalsh/.npm/_logs/2018-06-18T18_37_59_196Z-debug.log
```

**Comment by gauravprwl14** [comment]
@BobWalsh hi, its the issue with the latest version of the `node@10.2.1`, as its breaking when trying to install `fsevents` package. Can u install `node@8.10.0` which is stable and try again.

**Comment by aaronksaunders** [comment]
you need to run the commands specified in your terminal

```
  sudo sysctl -w kern.maxfiles=5242880
  sudo sysctl -w kern.maxfilesperproc=524288
```

**Comment by nuno** [comment]
Or you use @aaronksaunders  solution, which is correct.

Or in my case, I wanted solve this by install "Watchman" via Homebrew ( Homebrew is macOS only).
I remember that I had this issue in the past, and I solved this way, seems work.

```
$ brew update
$ brew install watchman
```

then run ....

`npm start  `

If you have all installed correctly,  should be work fine.
